import os

# Path to the notes directory
notes_dir = 'notes'

# List all .md files in the notes directory
note_files = [f for f in os.listdir(notes_dir) if f.endswith('.md')]

# Generate English markdown links
english_links = "\n- " + "\n- ".join([f"[{file.replace('.md', '')}](/notes/{file})" for file in note_files if '-en' in file])

# Generate Chinese markdown links
chinese_links = "\n- " + "\n- ".join([f"[{file.replace('.md', '')}](/notes/{file})" for file in note_files if '-zh' in file])

# Generate the English Post Markdown Content
english_content = f"""---
audio: true
lang: en
layout: post
title: notes
link: "pages/notes-zh"
---

These notes are primarily generated by AI chatbots. I used them to summarize key points and will walk through them to enhance my understanding.

{english_links}
"""

# Generate the Chinese Post Markdown Content
chinese_content = f"""---
audio: true
lang: zh
layout: post
title: 笔记
link: "pages/notes-en"
---

这些笔记主要由AI聊天机器人生成。我用它们来总结关键点，并通过阅读来加深理解。

{chinese_links}
"""

# Path to the pages directory
pages_dir = 'pages'

# Define the paths to the markdown files
english_file_path = os.path.join(pages_dir, 'notes-en.md')
chinese_file_path = os.path.join(pages_dir, 'notes-zh.md')

# Update the notes-en.md file with the generated English content
with open(english_file_path, 'w', encoding='utf-8') as english_file:
    english_file.write(english_content)

# Update the notes-zh.md file with the generated Chinese content
with open(chinese_file_path, 'w', encoding='utf-8') as chinese_file:
    chinese_file.write(chinese_content)

print(f"Updated {english_file_path} and {chinese_file_path}")
