import os
import frontmatter  # You need to install the 'python-frontmatter' package

# Path to the notes directory
notes_dir = 'notes'

# List all .md files in the notes directory
note_files = [f for f in os.listdir(notes_dir) if f.endswith('.md')]

# Initialize empty lists for English and Chinese links
english_links = []
chinese_links = []

# Parse each markdown file to extract the title and generate the links
for file in note_files:
    # Load the markdown file content and front matter
    with open(os.path.join(notes_dir, file), 'r', encoding='utf-8') as f:
        post = frontmatter.load(f)
        title = post.get('title', file.replace('.md', ''))  # Default to filename if no title is found
        
    # Generate the markdown link with the title and add an asterisk (*) in front
    link = f"* [{title}](/notes/{file})"
    
    # Sort links based on language (`-en` for English, `-zh` for Chinese)
    if '-en' in file:
        english_links.append(link)
    elif '-zh' in file:
        chinese_links.append(link)

# Generate the English Post Markdown Content
english_content = f"""---
audio: true
lang: en
layout: post
title: notes
link: "pages/notes-zh"
---

These notes are primarily generated by AI chatbots. I used them to summarize key points and will walk through them to enhance my understanding.

{chr(10).join(english_links)}
"""

# Generate the Chinese Post Markdown Content
chinese_content = f"""---
audio: true
lang: zh
layout: post
title: 笔记
link: "pages/notes-en"
---

这些笔记主要由AI聊天机器人生成。我用它们来总结关键点，并通过阅读来加深理解。

{chr(10).join(chinese_links)}
"""

# Path to the pages directory
pages_dir = 'pages'

# Define the paths to the markdown files
english_file_path = os.path.join(pages_dir, 'notes-en.md')
chinese_file_path = os.path.join(pages_dir, 'notes-zh.md')

# Update the notes-en.md file with the generated English content
with open(english_file_path, 'w', encoding='utf-8') as english_file:
    english_file.write(english_content)

# Update the notes-zh.md file with the generated Chinese content
with open(chinese_file_path, 'w', encoding='utf-8') as chinese_file:
    chinese_file.write(chinese_content)

print(f"Updated {english_file_path} and {chinese_file_path}")
